import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import CustomGTM from "./components/CustomGTM";
import { GoogleTagManager } from "@next/third-parties/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="custom" content="data" />
        <CustomGTM containerId="GTM-N2KPGC54" />
      </head>
      <body className={inter.className}>
        <noscript>
          <iframe
            src={`https://www.googletagmanager.com/ns.html?id=${"GTM-N2KPGC54"}`}
            height="0"
            width="0"
            style={{ display: "none", visibility: "hidden" }}
            title="Google Tag Manager"
          ></iframe>
        </noscript>
        {children}
      </body>
    </html>
  );
}
